<?xml version="1.0" encoding="UTF-8"?><testrun name="MemberMapperTest" project="TREEP" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="com.ss.sns.member.mapper.MemberMapperTest" time="0.41">
    <testcase name="memberSignup" classname="com.ss.sns.member.mapper.MemberMapperTest" time="0.41">
      <error>org.springframework.jdbc.BadSqlGrammarException: &#13;
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: ORA-00984: 열을 사용할 수 없습니다
&#13;
### The error may exist in file [C:\Users\User\git\TREEP\target\classes\mappers\member\member-mapper.xml]&#13;
### The error may involve defaultParameterMap&#13;
### The error occurred while setting parameters&#13;
### SQL: INSERT INTO MEMBER(MEMBER_NO,  MEMBER_ID,  MEMBER_PW,  MEMBER_NAME,  MEMBER_NICKNAME,  MEMBER_EMAIL,  MEMBER_BIRTH,  MEMBER_GENDER,  MEMBER_ENROLL,  MEMBER_PHONE,  MEMBER_TYPE,  MEMBER_IMG,  MEMBER_GRADE,  MANAGER_YN)  VALUES (  DEFAULT,  ?,  ?,  ?,  ?,  "alsehdns@naver.com",  null,  ?,  null,  ?,  ?,  '001.png',  null,   'N')&#13;
### Cause: java.sql.SQLSyntaxErrorException: ORA-00984: 열을 사용할 수 없습니다

; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: ORA-00984: 열을 사용할 수 없습니다
&#13;
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:93)&#13;
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)&#13;
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)&#13;
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)&#13;
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)&#13;
	at com.sun.proxy.$Proxy20.insert(Unknown Source)&#13;
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)&#13;
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)&#13;
	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:145)&#13;
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)&#13;
	at com.sun.proxy.$Proxy22.memberSignup(Unknown Source)&#13;
	at com.ss.sns.member.mapper.MemberMapperTest.memberSignup(MemberMapperTest.java:40)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)&#13;
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)&#13;
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)&#13;
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)&#13;
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
Caused by: java.sql.SQLSyntaxErrorException: ORA-00984: 열을 사용할 수 없습니다
&#13;
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:702)&#13;
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:608)&#13;
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1248)&#13;
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:1041)&#13;
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:443)&#13;
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:518)&#13;
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:251)&#13;
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1181)&#13;
	at oracle.jdbc.driver.OracleStatement.executeSQLStatement(OracleStatement.java:1571)&#13;
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1345)&#13;
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3728)&#13;
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3938)&#13;
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1011)&#13;
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94)&#13;
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94)&#13;
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)&#13;
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)&#13;
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)&#13;
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)&#13;
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)&#13;
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194)&#13;
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:181)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)&#13;
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)&#13;
	... 37 more&#13;
Caused by: Error : 984, Position : 263, SQL = INSERT INTO MEMBER(MEMBER_NO,
	MEMBER_ID,
	MEMBER_PW,
	MEMBER_NAME,
	MEMBER_NICKNAME,
	MEMBER_EMAIL,
	MEMBER_BIRTH,
	MEMBER_GENDER,
	MEMBER_ENROLL,
	MEMBER_PHONE,
	MEMBER_TYPE,
	MEMBER_IMG,
	MEMBER_GRADE,
	MANAGER_YN)
	VALUES (
	DEFAULT,
	:1 ,
	:2 ,
	:3 ,
	:4 ,
	"alsehdns@naver.com",
	null,
	:5 ,
	null,
	:6 ,
	:7 ,
	'001.png',
	null,
	 'N'), Original SQL = INSERT INTO MEMBER(MEMBER_NO,
	MEMBER_ID,
	MEMBER_PW,
	MEMBER_NAME,
	MEMBER_NICKNAME,
	MEMBER_EMAIL,
	MEMBER_BIRTH,
	MEMBER_GENDER,
	MEMBER_ENROLL,
	MEMBER_PHONE,
	MEMBER_TYPE,
	MEMBER_IMG,
	MEMBER_GRADE,
	MANAGER_YN)
	VALUES (
	DEFAULT,
	?,
	?,
	?,
	?,
	"alsehdns@naver.com",
	null,
	?,
	null,
	?,
	?,
	'001.png',
	null,
	 'N'), Error Message = ORA-00984: 열을 사용할 수 없습니다
&#13;
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:710)&#13;
	... 63 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
